FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD hyarel10.jar /opt/hyarel10/
EXPOSE 8080
WORKDIR /opt/hyarel10/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "hyarel10.jar"]
